engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths: []
- "public/javascripts/bootstrap-timepicker.js"
- "public/javascripts/bootstrap-timepicker.min.js"
